# Generated by Django 6.0.1 on 2026-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baito', '0002_rename_end_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hourly_wage',
            field=models.IntegerField(default=1000),
        ),
    ]
